spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:h2:mem:customer-db
  cloud:
    discovery:
      enabled: false
    config:
      discovery:
        enabled: false

server:
  port: 8056
